{
    "name": "Phone Number Validate",
    "version": "2.0",
    "summary": """Phone Number Validator""",
    "description": """Each customer have unique phone number, Odoo 13, Odoo""",
    "author": "xyz",
    "company": "xyz",
    "website": "https://kimbugp.github.io",
    "category": "Sales",
    "depends": ["sale"],
    "data": [],
    "demo": [],
    "license": "AGPL-3",
    "installable": True,
    "application": False,
}
